### PR TITLE
feat(approval): Add SNS topic for approval notifications

### PR DESCRIPTION
**Pull request by Nr18**
_Issue #, if available_: N/A

_Description of changes_:

Added a SNS Topic and configured it to receive the approval notifications so that you know you have to approve something.

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by heitorlessa** [comment]
Thanks for the nudge as I missed this @Nr18. Correct me if I'm wrong: There doesn't seem to be anywhere I can add my email if I want to be notified and I seem to have to go and subscribe to that topic (provided I know what SNS does for me).

If that's correct, mind making this explicit in the ``README.MD`` so they know what to do upon pipeline creation?

Thanks a lot as usual

**Comment by heitorlessa** [comment]
After that, we now have Tests for this project generation and would love to have one explicitly for the email functionality: https://github.com/aws-samples/cookiecutter-aws-sam-pipeline/blob/master/tests/test_cookiecutter.py

This would ensure that any changes in the template if one accidentally removes that from README or from the pipeline.yaml regardless of their Source Code choice we know the functionality is there.

Happy to provide guidance on how to write those integ tests if needed

**Comment by Nr18** [comment]
@heitorlessa ah will not be in the office tomorrow but when i get in i will have a look at the tests part you mentioned.

No i did not include a email but for this example i can add it as a template parameter and add the subscription. It demonstrates the purpose but i don't think it will be used in production typically you have multiple subscribers or other systems like slack... any thoughts?

**Comment by heitorlessa** [comment]
hey @Nr18 I had a discussion with a customer today on this and one angle I didn't immediately think about was the feedback that having a SNS topic will incur in costs while minimal it can be substantial for certain small customers and that will be a side effect --- publishing costs + delivery costs. 

I still believe this is a nice feature and not everyone is aware of that... what are your thoughts on adding a "Taking this to the next level" section under ``README.MD`` and explaining how to do this instead of having from the get go?

**Pull request closed without merging**
